spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhangjiaqi?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root

logging:
  level:
    com.example.dao: debug

mybatis:
  mapper-locations: classpath:mapperxml/*Mapper.xml